### ISSUE TITLE
SentencePiece error while running pre-processing

### ISSUE THREAD

**Issue by rhopatel** [FuxuWang/MHCRoBERTa#1]
`Traceback (most recent call last):
  File "/home/rohanp/MHCRoBERTa/process_MHC_pep.py", line 114, in <module>
    spm.SentencePieceTrainer.Train('--input=uniprot_pretraining_data.txt --model_prefix=m_reviewed_MHC --vocab_size=10000 --character_coverage=1.0 --model_type=bpe --max_sentence_length=1024')
  File "/home/rohanp/anaconda3/lib/python3.9/site-packages/sentencepiece/__init__.py", line 407, in Train
    return SentencePieceTrainer._TrainFromString(arg)
  File "/home/rohanp/anaconda3/lib/python3.9/site-packages/sentencepiece/__init__.py", line 385, in _TrainFromString
    return _sentencepiece.SentencePieceTrainer__TrainFromString(arg)
RuntimeError: Internal: src/trainer_interface.cc(406) [!sentences_.empty()] `

**Comment by rhopatel** [comment]
can i get any help here?

**Comment by xuanwuji** [comment]
I have the same problem.
